data_ = 'vwnd.sig995.4Xday.ltm.1991-2020.nc'
DATA_FILE = f'/data/srujan/research/catnipp/load_weather_data/{data_}' #air.sig995.mon.mean.nc ## rhum.mon.mean.nc' 
LAT_MIN = 0
LAT_MAX = 45
LON_MIN = 0
LON_MAX = 45
ROI_SIZE = 30
ENV_SIZE = 30
NORMALIZE_Y = True
RANDOM_ROI = True