BATCH_SIZE = 32 #8
INPUT_DIM = 4
EMBEDDING_DIM = 128
SAMPLE_SIZE = 200
K_SIZE = 20
BUDGET_RANGE = (8,10)
SAMPLE_LENGTH = 0.1

ADAPTIVE_AREA = True
ADAPTIVE_TH = 0.2

USE_GPU = True
USE_GPU_GLOBAL = True
CUDA_DEVICE = [1]
NUM_META_AGENT = 6 #32 #6
LR = 1e-4
GAMMA = 1
DECAY_STEP = 32
SUMMARY_WINDOW = 8
FOLDER_NAME = 'new_b_ard'
model_path = f'model/{FOLDER_NAME}'
train_path = f'train/{FOLDER_NAME}'
gifs_path = f'gifs/{FOLDER_NAME}'
LOAD_MODEL = False
SAVE_IMG_GAP = 10

FIXED_ENV= 2 